[package]
name = "oxidamp"
version = "0.2.0"
authors = ["Daniel Thompson"]
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
egui = "0.31.1"
egui-miniquad = "0.16.0"
itertools = "0.15.0"
jack = "0.13.5"
miniquad = "0.4.11"

[dev-dependencies]
bencher = "0.1.5"
cursive = { version = "0.21.1", default-features = false, features = ["crossterm-backend"] }
rand = "0.10.2"

[[bench]]
name = "main"
harness = false

[profile.bench]
debug = true
