// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2022 Daniel Thompson

use crate::*;

/// Longest delay line we can represent, in samples, and therefore the largest
/// excitation buffer we ever need (one period of the lowest note).
const MAX_PERIOD: usize = 1920;

/// Widest plectrum/finger contact, as a fraction of the string length. Used
/// when the pluck is at its softest and removes the most high frequency
/// energy.
const MAX_CONTACT: f32 = 0.04;

/// Narrowest contact, as a fraction of the string length. A hard, thin pick
/// leaves an almost ideal corner so the excitation keeps its full upper
/// harmonics.
const MIN_CONTACT: f32 = 0.004;

/// Front panel controls for a [KarplusStrong] voice.
///
/// The strike displacement is not here: that is supplied per note by the
/// velocity passed to [Voice::trigger].
#[derive(Clone, Copy, Debug)]
pub struct SynthConfig {
    /// Pluck point as a fraction of the string length from one end.
    pub position: f32,
    /// How strongly the strike displacement sharpens the pluck.
    pub hardness: f32,
    /// Loop gain, i.e. how long the string sustains.
    pub gain: f32,
}

impl Default for SynthConfig {
    fn default() -> Self {
        Self {
            position: 0.25,
            hardness: 0.6,
            gain: 0.999,
        }
    }
}

/// A plucked string voice.
///
/// This is a Karplus-Strong resonator excited with a physical model of the
/// pluck rather than a burst of noise.
///
/// Picking a string displaces it into (approximately) a triangle peaked at the
/// pluck point. The triangle is loaded into the delay line for one period and
/// then left to circulate through the loop filter, so the resonator rings with
/// the harmonics of that initial shape. For an ideal string of length normalised
/// to one, plucked a fraction `p` from the end with an initial displacement `d`,
/// the harmonic amplitudes are
///
/// ```text
/// A_n ∝ d / (n² · p(1-p)) · sin(nπp)
/// ```
///
/// which gives two of the classic, physically meaningful controls for free:
///
///  * the `sin(nπp)` term is a comb with nulls at harmonics `k/p`, so
///    [KarplusStrong::set_position] decides *which* harmonics are present
///    (pluck towards the bridge for a thin, bright tone; towards the middle for
///    a hollow, flute-like tone); and
///  * the `1/n²` term is the natural mellow tilt of a plucked string.
///
/// The remaining `d` is the strike displacement. In the ideal linear model it
/// is pure level, but a real pluck also gets brighter the harder it is played
/// (a larger displacement and a firmer pick leave a sharper corner at the
/// pluck point). The velocity passed to [Voice::trigger] sets `d`, so harder
/// notes are louder and - through [KarplusStrong::set_hardness] - brighter too.
#[derive(Debug)]
pub struct KarplusStrong {
    delay: FracDelay<MAX_PERIOD>,
    filter: FirstOrder,

    /// One period of initial string displacement, generated by [trigger].
    excite: [f32; MAX_PERIOD],
    excite_len: usize,
    excite_pos: usize,

    /// Pluck point as a fraction of the string length from one end, 0 < p < 1.
    position: f32,
    /// Strike displacement, i.e. how far/hard the string is pulled.
    strike: f32,
    /// How strongly the strike sharpens the pluck. 0 makes the strike pure
    /// level (ideal linear string); 1 makes a hard strike much brighter.
    hardness: f32,

    /// Loop period in samples, set by [Voice::tune].
    period: f32,
    /// Current loop gain.
    gain: f32,
    /// Level [Voice::trigger] resets the loop gain to.
    sustain: f32,
}

impl Default for KarplusStrong {
    fn default() -> Self {
        Self {
            delay: FracDelay::default(),
            filter: FirstOrder::default(),
            excite: [0.0; MAX_PERIOD],
            excite_len: 0,
            excite_pos: 0,
            position: 0.25,
            strike: 0.8,
            hardness: 0.6,
            period: 100.0,
            gain: 0.999,
            sustain: 0.999,
        }
    }
}

impl KarplusStrong {
    /// Set the loop gain, i.e. how long the string sustains.
    ///
    /// The gain is applied on every sample and controls how quickly the
    /// string decays; values closer to 1.0 sustain for longer. The value is
    /// also remembered as the level [Voice::trigger] resets to, so it doubles
    /// as the note's sustain.
    pub fn set_gain(&mut self, gain: f32) {
        self.gain = gain;
        self.sustain = gain;
    }

    /// Set the pluck point, as a fraction of the string length from one end.
    ///
    /// Values towards the ends give a thin, bright tone (harmonics at multiples
    /// of `1/p` are suppressed); a value near 0.5 plucks the middle and gives a
    /// hollow tone with the even harmonics missing. Applied on the next
    /// [Voice::trigger].
    pub fn set_position(&mut self, position: f32) {
        self.position = position.clamp(1.0e-3, 1.0 - 1.0e-3);
    }

    /// Set how strongly the strike displacement sharpens the pluck.
    ///
    /// At 0 the strike affects level only, as in an ideal linear string. At 1
    /// a hard strike leaves a very sharp corner and a lot of high frequency
    /// energy, while a light strike is rounded off and mellow. Applied on the
    /// next [Voice::trigger].
    pub fn set_hardness(&mut self, hardness: f32) {
        self.hardness = hardness.clamp(0.0, 1.0);
    }

    /// Apply a set of front panel controls.
    ///
    /// [KarplusStrong::set_position] and [KarplusStrong::set_hardness] take
    /// effect on the next [Voice::trigger]; the gain applies immediately.
    pub fn set_config(&mut self, config: SynthConfig) {
        self.set_position(config.position);
        self.set_hardness(config.hardness);
        self.set_gain(config.gain);
    }

    /// Build one period of initial string displacement into `excite`.
    fn build_excitation(&mut self) {
        let n = (self.period.round() as usize).clamp(2, MAX_PERIOD);
        let p = self.position.clamp(1.0e-3, 1.0 - 1.0e-3);

        // A firmer strike and/or a harder pick leave a sharper corner at the
        // pluck point. Model this as a one pole smoother over a fraction of the
        // period: a narrow contact barely rounds the corner (bright) and a wide
        // one rolls off the upper harmonics (mellow). Working in fractions of
        // the period keeps the character consistent across the register rather
        // than letting it drift with absolute frequency.
        let hardness = (self.strike * self.hardness).clamp(0.0, 1.0);
        let contact = MIN_CONTACT + (MAX_CONTACT - MIN_CONTACT) * (1.0 - hardness);
        let width = (contact * n as f32).max(0.25);
        let alpha = 1.0 - (-1.0 / width).exp();

        // Two passes: the first settles the smoother so the shape is smoothed
        // cyclically, with no discontinuity where the period wraps around.
        let mut y = 0.0;
        for i in 0..(2 * n) {
            let phase = (i % n) as f32 / n as f32;
            let tri = if phase < p {
                phase / p
            } else {
                (1.0 - phase) / (1.0 - p)
            };

            y += alpha * (tri - y);

            if i >= n {
                // The triangle's mean is exactly 1/2, so removing it excites no
                // DC mode. The factor of two restores the +/-strike peak.
                self.excite[i - n] = (y - 0.5) * 2.0 * self.strike;
            }
        }

        self.excite_len = n;
        self.excite_pos = 0;

        // Remove any residual DC exactly. The loop filter preserves DC, so a
        // non-zero mean would be amplified without bound once the loop gain is
        // allowed above 1 (see [KarplusStrong::set_half_life]).
        let sum: f64 = self.excite[..n].iter().map(|s| *s as f64).sum();
        let mean = (sum / n as f64) as f32;
        for s in &mut self.excite[..n] {
            *s -= mean;
        }
    }
}

impl Voice for KarplusStrong {
    fn setup(&mut self, ctx: &AudioContext) {
        self.delay.setup(ctx, 120.0);
        self.period = ctx.sampling_frequency as f32 / 120.0;
        self.filter.lowpass(ctx, ctx.sampling_frequency / 4);
    }

    fn trigger(&mut self, velocity: f32) {
        // Velocity is the strike displacement: pulling the string further
        // injects more energy and, through the hardness coupling, is also
        // brighter. Clamp so a velocity of 0 stays silent.
        self.strike = velocity.clamp(0.0, 1.0);
        self.build_excitation();
        self.gain = self.sustain;
    }

    fn mute(&mut self) {
        self.gain = 0.95;
    }

    fn tune(&mut self, ctx: &AudioContext, freq: f32) {
        // The loop is delay + filter. The first order low pass runs at
        // sampling_frequency / 4 which makes it a simple two tap average with
        // a group delay of half a sample, so the delay line itself must be
        // half a sample shorter than the desired period.
        let period = ctx.sampling_frequency as f32 / freq;
        self.delay.setup(ctx, period - 0.5);
        self.period = period;
    }
}

impl SignalGenerator for KarplusStrong {
    fn step(&mut self) -> f32 {
        let mut spl = if self.excite_pos < self.excite_len {
            let s = self.excite[self.excite_pos];
            self.excite_pos += 1;
            s
        } else {
            0.0
        };

        spl += self.gain * self.filter.step(self.delay.peek());
        let _ = self.delay.step(spl);

        spl
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::f32::consts::PI;

    /// Magnitude of the `h`-th harmonic of a periodic buffer.
    fn harmonic(x: &[f32], h: usize) -> f32 {
        let n = x.len();
        let (mut re, mut im) = (0.0_f32, 0.0_f32);

        for (i, s) in x.iter().enumerate() {
            let th = 2.0 * PI * h as f32 * i as f32 / n as f32;
            re += s * th.cos();
            im -= s * th.sin();
        }

        (re * re + im * im).sqrt()
    }

    fn excited(position: f32, velocity: f32, hardness: f32) -> KarplusStrong {
        let ctx = AudioContext::new(48000);
        let mut ks = KarplusStrong::default();
        ks.setup(&ctx);
        ks.set_position(position);
        ks.set_hardness(hardness);
        ks.tune(&ctx, 200.0);
        ks.trigger(velocity);
        ks
    }

    #[test]
    fn test_excitation_is_dc_free() {
        let ks = excited(0.3, 0.8, 0.5);
        let n = ks.excite_len;
        let mean: f32 = ks.excite[..n].iter().sum::<f32>() / n as f32;

        assert!(mean.abs() < 0.01, "mean {mean}");
    }

    #[test]
    fn test_pluck_position_comb() {
        // Plucking the midpoint suppresses the even harmonics.
        let ks = excited(0.5, 1.0, 0.0);
        let h1 = harmonic(&ks.excite[..ks.excite_len], 1);
        let h2 = harmonic(&ks.excite[..ks.excite_len], 2);

        assert!(h1 > 0.0);
        assert!(h2 < h1 * 0.05, "h1 {h1} h2 {h2}");
    }

    #[test]
    fn test_velocity_sets_level() {
        let quiet = excited(0.25, 0.25, 0.0);
        let loud = excited(0.25, 1.0, 0.0);
        let q1 = harmonic(&quiet.excite[..quiet.excite_len], 1);
        let l1 = harmonic(&loud.excite[..loud.excite_len], 1);

        assert!(l1 > q1 * 3.0, "quiet {q1} loud {l1}");
    }

    #[test]
    fn test_hardness_adds_top_end() {
        // p = 0.2 nulls harmonics at multiples of 5, so the 12th harmonic is
        // well clear of the comb and isolates the contact-width smoothing.
        let soft = excited(0.2, 1.0, 0.0);
        let hard = excited(0.2, 1.0, 1.0);
        let hs = harmonic(&soft.excite[..soft.excite_len], 12);
        let hh = harmonic(&hard.excite[..hard.excite_len], 12);

        assert!(hh > hs * 1.5, "soft {hs} hard {hh}");
    }

    #[test]
    fn test_config_applies_to_trigger() {
        let ctx = AudioContext::new(48000);
        let mut ks = KarplusStrong::default();
        ks.setup(&ctx);
        ks.tune(&ctx, 200.0);
        ks.set_config(SynthConfig {
            position: 0.4,
            hardness: 0.2,
            gain: 0.95,
        });
        ks.trigger(0.5);

        // The configured gain is what a new note sustains at.
        assert_eq!(ks.gain, 0.95);
        assert_eq!(ks.sustain, 0.95);
        assert!(ks.excite_len > 0);
    }
}
